### ISSUE TITLE
mobile menu

### ISSUE THREAD

**Issue by brody182** [woothemes/storefront#430]
if primary menu is disabled, secondary menu will not show in mobile menu.
tested on: mac os safari (latest) 
yes this is obviously a bug 

 I have both primary menu and secondary checked under appearance -> menus

if I remove the primary navigation, the secondary navigation does not show in mobile, however the secondary menu does show if the primary menu is enabled.

`remove_action( 'storefront_header', 'storefront_primary_navigation',               50 );`

**Comment by BurlesonBrad** [comment]
@brody182 In the initial screen, it mentioned to send in a system status.  I'm a bit intrigued as to why someone would simply **not** follow those instructions.  Can you help me comprehend that decision?

Are you looking for support or reporting a bug?

**Comment by brody182** [comment]
I dont see any system status options when submitting an issue

and yes this is a bug obviously

**Comment by opportus** [comment]
The secondary menu doesn't show by default even if the primary is enabled...

**Comment by brody182** [comment]
I assume you are doing testing on more than one browser or maybe you didn't think this through when developing the header menus

**Comment by opportus** [comment]
Which Storefront version are you using?

**Comment by brody182** [comment]
latest 2.0.5

**Comment by opportus** [comment]
https://github.com/woothemes/storefront/blob/master/assets/sass/components/_menu.scss#LC8

Looks like the secondary menu is not meant to be displayed on mobile device...

**Comment by BurlesonBrad** [comment]
right, but in #408 Caleb brought that up & Mike addressed it with https://github.com/woothemes/storefront/commit/8fa1a436672e12a014b4d3fb57e6794221527609

So, why it's not showing up for @brody182 is still a mystery.

**Comment by opportus** [comment]
Not sure their "issue" is related, @brody182 doesn't mention anywhere that he's trying to use "handled menu" by having checked it or so...
I don't know if it's my lack of english but his issue description is not clear at all to me.

**Comment by jameskoster** [comment]
The secondary menu has _never_ displayed on mobile.

**Comment by brody182** [comment]
@BurlesonBrad there is no Mysterious Conspiracy, all I'm doing is  removing the primary menu 
`remove_action( 'storefront_header', 'storefront_primary_navigation', 50 );`

**Comment by jameskoster** [comment]
Why don't you just add a menu to the `handheld` location @brody182 ?

**Comment by brody182** [comment]
yes I checked the handheld menu,  it does not work if I remove the primary menu.  What you have done is combined the primary menu and the handheld menu together so if I remove the primary menu nothing will show.

**Comment by jameskoster** [comment]
That's a separate issue, fixed here; https://github.com/woothemes/storefront/issues/408

**Comment by brody182** [comment]
you didn't fix anything, the primary and the secondary menus need to have separate functions

**Comment by jameskoster** [comment]
We fixed the issue that was reported.

Your issue (secondary nav displaying on mobile if no primary menu is set) is not an issue as the secondary menu has _never_ appeared on handheld. Use the handheld menu location for mobile.

Locking this now. If you have a genuine problem please open a new issue.
